added timeout as part of input
128technology/telegraf pull request #59
Opened 2023-09-29 15:03 UTC by shriyanshk128T

### Description ###

### Required for all PRs:

- [ ] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

2023-09-29 15:10 UTC, BenMatase requested changes

2023-09-29 15:10 UTC, BenMatase commented on plugins/outputs/execd/execd.go
> +	Timeout      time.Duration   `toml:"timeout"`
Can you make the default 5s?

2023-09-29 15:10 UTC, BenMatase commented on plugins/outputs/execd/execd.go
> +  timeout = 0
And then make the sample configs `timeout = 5s`

2023-09-29 15:10 UTC, BenMatase commented on plugins/inputs/execd/README.md
> +  ## Timeout
Make a bit more descriptive. Something like `Timeout given to process when gracefully shutting down`

2023-09-29 15:11 UTC, BenMatase commented on plugins/inputs/execd/README.md
> +  timeout = 0
Can we make this `shutdown_timeout`?

2023-09-29 17:42 UTC, BenMatase commented on internal/process/process.go
> +			gracefulStop(processCtx, p.Cmd, shutdownTimeout*time.Second)
You don't need the *time Second. In fact it might make it incorrect

2023-09-29 17:42 UTC, BenMatase commented on plugins/inputs/execd/execd.go
> +			ShutdownTimeout: 5,
Specify the *time.Second here

2023-09-29 17:42 UTC, BenMatase commented on plugins/inputs/execd/execd_test.go
> +		shutdown_timeout = 5
This should be "5s" in all of the tomls

2023-09-30 00:12 UTC, agrawalkaushik approved these changes

2023-10-02 12:33 UTC, BenMatase approved these changes

2023-10-02 12:33 UTC, BenMatase commented on plugins/inputs/execd/execd_test.go
> +		shutdown_timeout = "5s"
nit: can you do a value that isn't the default to make sure it isn't just using the default?

2023-10-02 13:16 UTC, gregschrock approved these changes

2023-10-02 13:17 UTC, gregschrock commented
Please use "Squash" when merging the PR

2023-10-02 16:55 UTC, merged